package spatutorial.client.components

import diode.data.Pot
import diode.react.{ModelProxy, ReactConnectProxy}
import japgolly.scalajs.react.CompScope._
import japgolly.scalajs.react._
import japgolly.scalajs.react.vdom.Builder
import japgolly.scalajs.react.vdom.prefix_<^._
import spatutorial.client.services.Services

import scala.scalajs.js



case class IdProvider(child: TagMod, id: String, searchString: String) extends TagMod{
//  val stringify = id //!@ beef this up to be generated by the component

  override def applyTo(b: Builder): Unit = child.applyTo(b)
}

object IdProvider {
  val empty = IdProvider(<.span("EMPTY EGG"), "no-id", "no-search-string")
}

case class TreeItem(item: IdProvider, children: TreeItem*) {
  def apply(item: IdProvider): TreeItem = TreeItem(item, Nil:_*)
}
//case class TreeItem(item: IdProvider , children: TreeItem*) {
//  def apply(item: Any): TreeItem = this(item, Nil)
//}

object ReactTreeView {

  trait Style {

    def reactTreeView = Seq[TagMod]()

    def treeGroup = Seq(^.margin := 0, ^.padding := "0 0 0 14px")

    def treeItem = Seq(^.listStyleType := "none")

    def selectedTreeItemContent = Seq( //^.backgroundColor := "#1B8EB0",
      ^.color := "blue", ^.fontWeight := 400,
      ^.padding := "0 19px")

    def treeItemBefore = Seq(
      ^.display := "inline-block",
      ^.fontSize := "11px",
      ^.color := "grey",
      ^.margin := "3px 7px 0 0",
      ^.textAlign := "center",
      ^.width := "11px"
    )

//    def treeItemHasChildrenClosed = Seq(^.contentStyle := "▶")
//
//    def treeItemHasChildrenOpened = Seq(^.contentStyle := "▼")

  }

  type NodeC = DuringCallbackU[NodeProps, NodeState, NodeBackend]

  case class State(treeItemConnector : ReactConnectProxy[TreeItem],
                    filterText: String,
                   filterMode: Boolean,
                   selectedNode: js.UndefOr[NodeC])

  class Backend($: BackendScope[Props, State]) {

    def onNodeSelect(P: Props)(selected: NodeC): Callback = {
      val removeSelection: Callback =
        $.state.flatMap(
          _.selectedNode
            .filterNot(_ == selected)
            .filter(_.isMounted())
            .fold(Callback.empty)(_.modState(_.copy(selected = false)))
        )

      val updateThis: Callback =
        $.modState(_.copy(selectedNode = selected, filterMode = false))

      val setSelection: Callback =
        selected.modState(_.copy(selected = true))

      val tell: Callback =
        P.onItemSelect.asCbo(
          selected.props.root.item.id,
          selected.props.parent,
          selected.props.depth
        )

      removeSelection >> updateThis >> setSelection >> tell
    }

    def onTextChange(text: String): Callback =
      $.modState(_.copy(filterText = text, filterMode = true))

    def render(P: Props, S: State) = {
      println(s"ReactTreeView backend render.....")

        <.div(P.style.reactTreeView)(
          P.showSearchBox ?= ReactSearchBox(onTextChange = onTextChange),
          S.treeItemConnector((m: ModelProxy[TreeItem]) =>
            TreeNode.withKey("root")(NodeProps(
            root         = m.value, //P.pimpedRoot,
            open         = if (S.filterText.nonEmpty) true else P.open,
            onNodeSelect = onNodeSelect(P),
            filterText   = S.filterText,
            style        = P.style,
            filterMode   = S.filterMode
          ))
        )
        )


    }
  }

  case class NodeBackend($: BackendScope[NodeProps, NodeState]) {

    def onItemSelect(P: NodeProps)(e: ReactEventH): Callback =
      P.onNodeSelect($.asInstanceOf[NodeC]) >> e.preventDefaultCB >> e.stopPropagationCB

    def childrenFromProps(P: NodeProps): CallbackTo[Option[Unit]] =
      $.modState(S => S.copy(children = if (S.children.isEmpty) P.root.children else Nil))
        .conditionally(P.root.children.nonEmpty)

    def onTreeMenuToggle(P: NodeProps)(e: ReactEventH): Callback =
      childrenFromProps(P) >> e.preventDefaultCB >> e.stopPropagationCB

    def isFilterTextExist(filterText: String, data: TreeItem): Boolean = {
      def matches(item: TreeItem): Boolean =
        item.item.searchString.toLowerCase.contains(filterText.toLowerCase)

      def loop(data: Seq[TreeItem]): Boolean =
        data.view.exists(
          item => if (item.children.isEmpty) matches(item) else loop(item.children)
        )

      matches(data) || loop(data.children)
    }

    def render(P: NodeProps, S: NodeState): ReactTag = {
      println(s"ReactTreeView nodeBackend render children of root")
      val depth    = P.depth + 1
//      val parent   = P.root.item.id

      val parent = if (P.parent.isEmpty) P.root.item.id
                   else s"${P.parent}<-${P.root.item.id}"

      val treeMenuToggle: TagMod =
        if (S.children.nonEmpty)
          <.a(
            ^.onClick ==> onTreeMenuToggle(P),
            ^.key := "arrow",
            P.style.treeItemBefore,
//            "▼",
//            Icon.arrowCircleDown2x,
            Icon.arrowCircleODown2x
          )
        else if (P.root.children.nonEmpty && S.children.isEmpty)
          <.a(
            ^.onClick ==> onTreeMenuToggle(P),
            ^.key := "arrow",
            P.style.treeItemBefore,
//            "▶"
              Icon.arrowCircleORight2x
          )
        else ""

      <.li(
        P.style.treeItem,
        treeMenuToggle,
        ^.key := "toggle",
        ^.cursor := "pointer",
        <.span(
          S.selected ?= P.style.selectedTreeItemContent,
          ^.onClick ==> onItemSelect(P),
//!@          P.root.item.toString
          P.root.item
        ),
        <.ul(P.style.treeGroup)(
          S.children.map(child =>
            isFilterTextExist(P.filterText, child) ?=
              TreeNode.withKey(s"$parent$depth${child.item}")(P.copy(
                root = child,
                open = !P.filterText.trim.isEmpty,
                depth = depth,
                parent = parent,
                filterText = P.filterText
              ))
          ))
      )
    }
  }

  case class NodeState(children: Seq[TreeItem] = Nil, selected: Boolean = false)

  case class NodeProps(root: TreeItem,
                       open: Boolean,
                       depth: Int = 0,
                       parent: String = "",
                       onNodeSelect: (NodeC) => Callback,
                       filterText: String,
                       style: Style,
                       filterMode: Boolean)

  lazy val TreeNode = ReactComponentB[NodeProps]("ReactTreeNode")
    .initialState_P { P =>

      if (P.open) NodeState(P.root.children) else NodeState()
    }
    .renderBackend[NodeBackend]
    .componentWillReceiveProps {
      case ComponentWillReceiveProps(_$, newProps) =>
        println(s"Tree node got new props: $newProps")
        js.debugger()
//        _$.modState(_.copy(children = if (newProps.open) newProps.root.children else Nil))
        _$.modState(_.copy(children = newProps.root.children))
          .conditionally(newProps.filterMode)
          .void
    }
    .build

  val component = ReactComponentB[Props]("ReactTreeView")
    .initialState_P(p => State(p.proxy.connect(identity), "", true, js.undefined))
    .renderBackend[Backend]
    .build

  case class Props(proxy: ModelProxy[TreeItem],
//                   pimpedRoot: TreeItem,
                   open: Boolean,
                   onItemSelect: js.UndefOr[(String, String, Int) => Callback],
                   showSearchBox: Boolean,
                   style: Style)

  def apply(proxy: ModelProxy[TreeItem],
//             pimpedRoot: TreeItem,
            openByDefault: Boolean = false,
            onItemSelect: js.UndefOr[(String, String, Int) => Callback] = js.undefined,
            showSearchBox: Boolean = false,
            ref: js.UndefOr[String] = js.undefined,
            key: js.UndefOr[js.Any] = js.undefined,
            style: Style = new Style {}) =
    component.set(key, ref)(Props(proxy, openByDefault, onItemSelect, showSearchBox, style))

}
